name = "ruixen"
type = "javascript"

account_id = "8295318475ba63f2e236f8b35d3682c1"
workers_dev = true
compatibility_date = "2024-07-01"

# Uncomment this after domain is linked
# routes = ["https://ruixen.com/*"]

[assets]
directory = "./out"