import { MainNavItem, SidebarNavItem } from "@/types";

interface DocsConfig {
  mainNav: MainNavItem[];
  sidebarNav: SidebarNavItem[];
}

export const docsConfig: DocsConfig = {
  mainNav: [
    {
      title: "Components",
      href: "/docs/components",
    },
    {
      title: "Templates",
      href: "/templates",
      event: "header_cta_clicked",
      label: "",
    },
    {
      title: "Gradients",
      href: "/gradients",
      event: "gradients_clicked",
      label: "",
    },
    {
      title: "Generator",
      href: "/",
      event: "header_cta_clicked",
      label: "New",
      items: [
        {
          title: "Glass Morphism",
          href: "/generator/glass-morphism",
        },
        {
          title: "Shadow Generator",
          href: "/generator/shadow-generator",
          label: "",
        },
        {
          title: "CSS Gradient Generator",
          href: "/generator/css-generator",
          label: "",
        },
      ],
    },
    {
      title: "Blog",
      href: "/blog",
      event: "header_cta_clicked",
      label: "",
    },
    {
      title: "Supporters",
      href: "/supporters",
      event: "header_cta_clicked",
      label: "New",
    },
  ],
  sidebarNav: [
    {
      title: "Getting Started",
      items: [
        {
          title: "Introduction",
          href: "/docs",
          items: [],
        },
        {
          title: "Installation",
          href: "/docs/installation",
          items: [
            {
              title: "Next.js",
              href: `/docs/installation/next`,
              items: [],
            },
            {
              title: "Vite",
              href: `/docs/installation/vite`,
              items: [],
            },
            {
              title: "Remix",
              href: `/docs/installation/remix`,
              items: [],
            },
            {
              title: "Astro",
              href: `/docs/installation/astro`,
              items: [],
            },
            {
              title: "Laravel",
              href: `/docs/installation/laravel`,
              items: [],
            },
            {
              title: "Gatsby",
              href: `/docs/installation/gatsby`,
              items: [],
            },
            {
              title: "Manual",
              href: `/docs/installation/manual`,
              items: [],
            },
          ],
        },
        // {
        //   title: "Tailwind v4",
        //   href: "/docs/tailwind-v4",
        //   items: [],
        //   label: "",
        // },
        // {
        //   title: "MCP",
        //   href: "/docs/mcp",
        //   items: [],
        //   label: "",
        // },
      ],
    },
    {
      title: "Templates",
      items: [
        {
          title: "Portfolio",
          href: `/docs/templates/portfolio`,
          items: [],
          label: "",
          event: "template_portfolio_clicked",
        },
      ],
    },
    {
      title: "Components",
      items: [
        {
          title: "Cards",
          items: [
            {
              title: "Precision Card",
              href: `/docs/components/precision-card`,
              items: [],
              label: "",
            },
            {
              title: "Social Card",
              href: `/docs/components/social-card`,
              items: [],
              label: "",
            },
            {
              title: "Portfolio Card",
              href: `/docs/components/portfolio-card`,
              items: [],
              label: "",
            },
            {
              title: "Job Card",
              href: `/docs/components/job-card`,
              items: [],
              label: "",
            },
            {
              title: "Team Project Card",
              href: `/docs/components/team-project-card`,
              items: [],
              label: "",
            },
            {
              title: "Collab Chat Card",
              href: `/docs/components/collab-chat-card`,
              items: [],
              label: "",
            },
            {
              title: "Goal Tracker Card",
              href: `/docs/components/goal-tracker-card`,
              items: [],
              label: "",
            },
            {
              title: "Environment Card",
              href: `/docs/components/environment-card`,
              items: [],
              label: "",
            },
            {
              title: "Schedule Card",
              href: `/docs/components/schedule-card`,
              items: [],
              label: "",
            },
            {
              title: "Showcase Card",
              href: `/docs/components/showcase-card`,
              items: [],
              label: "",
            },
            {
              title: "Order Summary Card",
              href: `/docs/components/order-summary-card`,
              items: [],
              label: "",
            },
            {
              title: "Doctor Profile Card",
              href: `/docs/components/doctor-profile-card`,
              items: [],
              label: "",
            },
            {
              title: "Gradient Blob Card",
              href: `/docs/components/gradient-blob-card`,
              items: [],
              label: "",
            },
            {
              title: "Idea Generator Card",
              href: `/docs/components/idea-generator-card`,
              items: [],
              label: "",
            },
            {
              title: "Elite Plan Card",
              href: `/docs/components/elite-plan-card`,
              items: [],
              label: "",
            },
            {
              title: "Shirt Parallax Card",
              href: `/docs/components/shirt-parallax-card`,
              items: [],
              label: "",
            },
            {
              title: "Order Tracking Parallax Card",
              href: `/docs/components/order-tracking-parallax-card`,
              items: [],
              label: "",
            },
            {
              title: "Product Bounce Card",
              href: `/docs/components/product-bounce-card`,
              items: [],
              label: "",
            },
            {
              title: "Credit Card Hero",
              href: `/docs/components/credit-card-hero`,
              items: [],
              label: "",
            },
            {
              title: "Verification Card",
              href: `/docs/components/verification-card`,
              items: [],
              label: "",
            },
            {
              title: "Project Progress Card",
              href: `/docs/components/project-progress-card`,
              items: [],
              label: "",
            },
            {
              title: "Health Stat Card",
              href: `/docs/components/health-stat-card`,
              items: [],
              label: "",
            },
            {
              title: "Card Stack",
              href: `/docs/components/card-stack`,
              items: [],
              label: "New",
            },
          ],
        },
        {
          title: "Buttons",
          items: [
            {
              title: "Slide To Delete Button",
              href: `/docs/components/slide-to-delete-button`,
              items: [],
              label: "",
            },
            {
              title: "Glow Link Button",
              href: `/docs/components/glow-link-button`,
              items: [],
              label: "",
            },
            {
              title: "Theme Cycle Button",
              href: `/docs/components/theme-cycle-button`,
              items: [],
              label: "",
            },
            {
              title: "Morphing Github Button",
              href: `/docs/components/morphing-github-button`,
              items: [],
              label: "",
            },
            {
              title: "Multi State Morph Button",
              href: `/docs/components/multi-state-morph-button`,
              items: [],
              label: "",
            },
            {
              title: "Dynamic Status Button",
              href: `/docs/components/dynamic-status-button`,
              items: [],
              label: "",
            },
            {
              title: "Hover Preview Button",
              href: `/docs/components/hover-preview-button`,
              items: [],
              label: "",
            },
            {
              title: "Segmented Button Group",
              href: `/docs/components/segmented-button-group`,
              items: [],
              label: "",
            },
            {
              title: "Confetti Button",
              href: `/docs/components/confetti-button`,
              items: [],
              label: "",
            },
            {
              title: "Swipe To Confirm Button",
              href: `/docs/components/swipe-to-confirm-button`,
              items: [],
              label: "",
            },
            {
              title: "Status Button",
              href: `/docs/components/status-button`,
              items: [],
              label: "",
            },
            {
              title: "Checklist Button",
              href: `/docs/components/checklist-button`,
              items: [],
              label: "",
            },
            {
              title: "Countdown Button",
              href: `/docs/components/countdown-button`,
              items: [],
              label: "",
            },
            {
              title: "Icon Grid Button",
              href: `/docs/components/icon-grid-button`,
              items: [],
              label: "",
            },
            {
              title: "Multi Step Button",
              href: `/docs/components/multi-step-button`,
              items: [],
              label: "",
            },
            {
              title: "Tooltip Button",
              href: `/docs/components/tooltip-button`,
              items: [],
              label: "",
            },
            {
              title: "Badge Button Combo",
              href: `/docs/components/badge-button-combo`,
              items: [],
              label: "",
            },
            {
              title: "Expandable Content Button",
              href: `/docs/components/expandable-content-button`,
              items: [],
              label: "",
            },
            {
              title: "Notification Button",
              href: `/docs/components/notification-button`,
              items: [],
              label: "",
            },
            {
              title: "Confirmation Button",
              href: `/docs/components/confirmation-button`,
              items: [],
              label: "",
            },
            {
              title: "Avatar Action Button",
              href: `/docs/components/avatar-action-button`,
              items: [],
              label: "",
            },
            {
              title: "Split Action Button",
              href: `/docs/components/split-action-button`,
              items: [],
              label: "",
            },
            {
              title: "Progress Button",
              href: `/docs/components/progress-button`,
              items: [],
              label: "",
            },
            {
              title: "Icon Label Subtext Button",
              href: `/docs/components/icon-label-subtext-button`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Loaders",
          items: [
            {
              title: "Loading Circle",
              href: `/docs/components/loading-circle`,
              items: [],
              label: "",
            },
            {
              title: "Load Ripple",
              href: `/docs/components/load-ripple`,
              items: [],
              label: "",
            },
            {
              title: "Ripple Circles",
              href: `/docs/components/ripple-circles`,
              items: [],
              label: "",
            },
            {
              title: "Solar Loader",
              href: `/docs/components/solar-loader`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Dialogs",
          items: [
            {
              title: "Credit Card Dialog",
              href: `/docs/components/credit-card-dialog`,
              items: [],
              label: "",
            },
            {
              title: "Identity Verification Dialog",
              href: `/docs/components/identity-verification-dialog`,
              items: [],
              label: "",
            },
            {
              title: "Add Task Sheet",
              href: `/docs/components/add-task-sheet`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Upload Components",
          items: [
            {
              title: "Music Equalizer Upload",
              href: `/docs/components/music-equalizer-upload`,
              items: [],
              label: "",
            },
            {
              title: "Sketchpad Dropzone",
              href: `/docs/components/sketchpad-dropzone`,
              items: [],
              label: "",
            },
            {
              title: "Stacked Cards Upload",
              href: `/docs/components/stacked-cards-upload`,
              items: [],
              label: "",
            },
            {
              title: "Timeline Upload",
              href: `/docs/components/timeline-upload`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Breadcrumb",
          items: [
            {
              title: "Smart Breadcrumb",
              href: `/docs/components/smart-breadcrumb`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Audio & Media",
          items: [
            {
              title: "Audio Timeline With Chapters",
              href: `/docs/components/audio-timeline-with-chapters`,
              items: [],
              label: "",
            },
            {
              title: "Playlist Carousel",
              href: `/docs/components/playlist-carousel`,
              items: [],
              label: "",
            },
            {
              title: "Voice Message Bubble",
              href: `/docs/components/voice-message-bubble`,
              items: [],
              label: "",
            },
            {
              title: "Visualizer Button",
              href: `/docs/components/visualizer-button`,
              items: [],
              label: "",
            },
            {
              title: "Audio Book Player",
              href: `/docs/components/audio-book-player`,
              items: [],
              label: "",
            },
            {
              title: "Podcast Card Player",
              href: `/docs/components/podcast-card-player`,
              items: [],
              label: "",
            },
            {
              title: "Waveform Player",
              href: `/docs/components/waveform-player`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Select Components",
          items: [
            {
              title: "Color Emotion Select",
              href: `/docs/components/color-emotion-select`,
              items: [],
              label: "",
            },
            {
              title: "Tag Cloud Select",
              href: `/docs/components/tag-cloud-select`,
              items: [],
              label: "",
            },
            {
              title: "Live Preview Style Select",
              href: `/docs/components/live-preview-style-select`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Chat Components",
          items: [
            {
              title: "Ruixen Moon Chat",
              href: `/docs/components/ruixen-moon-chat`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Inputs",
          items: [
            {
              title: "Circular Stepper Input",
              href: `/docs/components/circular-stepper-input`,
              items: [],
              label: "",
            },
            {
              title: "Password Strength Input",
              href: `/docs/components/password-strength-input`,
              items: [],
              label: "",
            },
            {
              title: "OTP Input",
              href: `/docs/components/otp-input`,
              items: [],
              label: "",
            },
            {
              title: "Color Picker Input",
              href: `/docs/components/color-picker-input`,
              items: [],
              label: "",
            },
            {
              title: "Gravatar Email Input",
              href: `/docs/components/gravatar-email-input`,
              items: [],
              label: "",
            },
            {
              title: "Correct Number Input",
              href: `/docs/components/correct-number-input`,
              items: [],
              label: "",
            },
            {
              title: "Better Time Picker",
              href: `/docs/components/better-time-picker`,
              items: [],
              label: "",
            },
            {
              title: "Inline Copy Input",
              href: `/docs/components/inline-copy-input`,
              items: [],
              label: "",
            },
            {
              title: "Clean Tag Input",
              href: `/docs/components/clean-tag-input`,
              items: [],
              label: "",
            },
            {
              title: "Search With Category",
              href: `/docs/components/search-with-category`,
              items: [],
              label: "",
            },
            {
              title: "Input With Select",
              href: `/docs/components/input-with-select`,
              items: [],
              label: "",
            },
            {
              title: "Range Slider Input",
              href: `/docs/components/range-slider-input`,
              items: [],
              label: "",
            },
            {
              title: "URL Input",
              href: `/docs/components/url-input`,
              items: [],
              label: "",
            },
            {
              title: "Floating Input",
              href: `/docs/components/floating-input`,
              items: [],
              label: "",
            },
            {
              title: "Time With Icon",
              href: `/docs/components/time-with-icon`,
              items: [],
              label: "",
            },
            {
              title: "OTP Field",
              href: `/docs/components/otp-field`,
              items: [],
              label: "",
            },
            {
              title: "Modern Card Input",
              href: `/docs/components/modern-card-input`,
              items: [],
              label: "",
            },
            {
              title: "Password Field",
              href: `/docs/components/password-field`,
              items: [],
              label: "",
            },
            {
              title: "Smart Assist Input",
              href: `/docs/components/smart-assist-input`,
              items: [],
              label: "",
            },
            {
              title: "Action Hub Input",
              href: `/docs/components/action-hub-input`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Notifications",
          items: [
            {
              title: "Smart Notify Button",
              href: `/docs/components/smart-notify-button`,
              items: [],
              label: "",
            },
            {
              title: "Cookie Notice",
              href: `/docs/components/cookie-notice`,
              items: [],
              label: "",
            },
            {
              title: "Notification Badge",
              href: `/docs/components/notification-badge`,
              items: [],
              label: "",
            },
            {
              title: "Notifications Popover",
              href: `/docs/components/notifications-popover`,
              items: [],
              label: "",
            },
            {
              title: "Notification Inbox Popover",
              href: `/docs/components/notification-inbox-popover`,
              items: [],
              label: "",
            },
            {
              title: "Tour Popover",
              href: `/docs/components/tour-popover`,
              items: [],
              label: "",
            },
            {
              title: "Notification",
              href: `/docs/components/notification`,
              items: [],
              label: "",
            },
            {
              title: "Notification Alt",
              href: `/docs/components/notification-alt`,
              items: [],
              label: "",
            },
            {
              title: "Notifications With Actions",
              href: `/docs/components/notifications-with-actions`,
              items: [],
              label: "",
            },
            {
              title: "Notifications Carousel",
              href: `/docs/components/notifications-carousel`,
              items: [],
              label: "",
            },
            {
              title: "Notification Toggle",
              href: `/docs/components/notification-toggle`,
              items: [],
              label: "",
            },
            {
              title: "Notifications Filter",
              href: `/docs/components/notifications-filter`,
              items: [],
              label: "",
            },
            {
              title: "Avatar Notifications",
              href: `/docs/components/avatar-notifications`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Menu",
          items: [
            {
              title: "Nested Dashboard Menu",
              href: `/docs/components/nested-dashboard-menu`,
              items: [],
              label: "",
            },
            {
              title: "App Menu Bar",
              href: `/docs/components/app-menu-bar`,
              items: [],
              label: "",
            },
            {
              title: "Account Menu",
              href: `/docs/components/account-menu`,
              items: [],
              label: "",
            },
            {
              title: "Action Toolbar",
              href: `/docs/components/action-toolbar`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Context Menu",
          items: [
            {
              title: "Advanced Context Menu",
              href: `/docs/components/advanced-context-menu`,
              items: [],
              label: "",
            },
            {
              title: "User Context Menu",
              href: `/docs/components/user-context-menu`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Drawer",
          items: [
            {
              title: "Drawer Inner Content",
              href: `/docs/components/drawer-inner-content`,
              items: [],
              label: "",
            },
            {
              title: "Centered Feedback Drawer",
              href: `/docs/components/centered-feedback-drawer`,
              items: [],
              label: "",
            },
            {
              title: "Bottom Drawers",
              href: `/docs/components/bottom-drawers`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Forms",
          items: [
            {
              title: "Sign In Form",
              href: `/docs/components/sign-in-form`,
              items: [],
              label: "",
            },
            {
              title: "Create Account Form",
              href: `/docs/components/create-account-form`,
              items: [],
              label: "",
            },
            {
              title: "Newsletter Form",
              href: `/docs/components/newsletter-form`,
              items: [],
              label: "",
            },
            {
              title: "Sign In Card",
              href: `/docs/components/sign-in-card`,
              items: [],
              label: "",
            },
            {
              title: "Flip Card",
              href: `/docs/components/flip-card`,
              items: [],
              label: "",
            },
            {
              title: "Success Login Card",
              href: `/docs/components/success-login-card`,
              items: [],
              label: "",
            },
            {
              title: "Step Card",
              href: `/docs/components/step-card`,
              items: [],
              label: "",
            },
            {
              title: "Radio Group Card",
              href: `/docs/components/radio-group-card`,
              items: [],
              label: "",
            },
            {
              title: "Emoji Radio Group",
              href: `/docs/components/emoji-radio-group`,
              items: [],
              label: "",
            },
            {
              title: "Sentiment Radio Group",
              href: `/docs/components/sentiment-radio-group`,
              items: [],
              label: "",
            },
            {
              title: "Rating Scale Group",
              href: `/docs/components/rating-scale-group`,
              items: [],
              label: "",
            },
            {
              title: "Review Filter Bars",
              href: `/docs/components/review-filter-bars`,
              items: [],
              label: "",
            },
            {
              title: "Auth Tabs Card",
              href: `/docs/components/auth-tabs-card`,
              items: [],
              label: "",
            },
            {
              title: "Gamified Login Card",
              href: `/docs/components/gamified-login-card`,
              items: [],
              label: "",
            },
            {
              title: "Social Auth Card",
              href: `/docs/components/social-auth-card`,
              items: [],
              label: "",
            },
            {
              title: "Login Card",
              href: `/docs/components/login-card`,
              items: [],
              label: "",
            },
            {
              title: "Multi Step Login",
              href: `/docs/components/multi-step-login`,
              items: [],
              label: "",
            },
            {
              title: "Split Login Card",
              href: `/docs/components/split-login-card`,
              items: [],
              label: "",
            },
            {
              title: "Cloud Watch Form",
              href: `/docs/components/cloud-watch-form`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "File Management",
          items: [
            {
              title: "File Tree Manager",
              href: `/docs/components/file-tree-manager`,
              items: [],
              label: "",
            },
            {
              title: "Motion File Tree",
              href: `/docs/components/motion-file-tree`,
              items: [],
              label: "",
            },
            {
              title: "Magic Tree",
              href: `/docs/components/magic-tree`,
              items: [],
              label: "",
            },
            {
              title: "Tree Node Tooltip",
              href: `/docs/components/tree-node-tooltip`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Tables",
          items: [
            {
              title: "Sortable Table",
              href: `/docs/components/sortable-table`,
              items: [],
              label: "",
            },
            {
              title: "Table Edit",
              href: `/docs/components/table-edit`,
              items: [],
              label: "",
            },
            {
              title: "Table With Dialog",
              href: `/docs/components/table-with-dialog`,
              items: [],
              label: "",
            },
            {
              title: "Fixed Header Footer Table",
              href: `/docs/components/fixed-header-footer-table`,
              items: [],
              label: "",
            },
            {
              title: "Reorderable Table",
              href: `/docs/components/reorderable-table`,
              items: [],
              label: "",
            },
            {
              title: "Comparison Table",
              href: `/docs/components/comparison-table`,
              items: [],
              label: "",
            },
            {
              title: "Flexi Filter Table",
              href: `/docs/components/flexi-filter-table`,
              items: [],
              label: "",
            },
            {
              title: "Table Dialog",
              href: `/docs/components/table-dialog`,
              items: [],
              label: "",
            },
            {
              title: "Minimisable Table",
              href: `/docs/components/minimisable-table`,
              items: [],
              label: "",
            },
            {
              title: "Inline Analytics Table",
              href: `/docs/components/inline-analytics-table`,
              items: [],
              label: "",
            },
            {
              title: "Column Collaboration Table",
              href: `/docs/components/column-collaboration-table`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Date Pickers",
          items: [
            {
              title: "Date Time Picker",
              href: `/docs/components/date-time-picker`,
              items: [],
              label: "",
            },
            {
              title: "Date Range Picker",
              href: `/docs/components/date-range-picker`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Calendars",
          items: [
            {
              title: "Monthly Heatmap Calendar",
              href: `/docs/components/monthly-heatmap-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Multi Month Calendar",
              href: `/docs/components/multi-month-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Calendar With Presets",
              href: `/docs/components/calendar-with-presets`,
              items: [],
              label: "",
            },
            {
              title: "Universal Date Picker",
              href: `/docs/components/universal-date-picker`,
              items: [],
              label: "",
            },
            {
              title: "Date Time Input",
              href: `/docs/components/date-time-input`,
              items: [],
              label: "",
            },
            {
              title: "Dropdown Range Date Picker",
              href: `/docs/components/dropdown-range-date-picker`,
              items: [],
              label: "",
            },
            {
              title: "Dropdown Multi Calendar",
              href: `/docs/components/dropdown-multi-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Multi Select Calendar Card",
              href: `/docs/components/multi-select-calendar-card`,
              items: [],
              label: "",
            },
            {
              title: "Side Panel Multi Calendar",
              href: `/docs/components/side-panel-multi-calendar`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Event Calendars",
          items: [
            {
              title: "Event Scheduler",
              href: `/docs/components/event-scheduler`,
              items: [],
              label: "",
            },
            {
              title: "Scheduler",
              href: `/docs/components/scheduler`,
              items: [],
              label: "",
            },
            {
              title: "Daily Timeline Scheduler",
              href: `/docs/components/daily-timeline-scheduler`,
              items: [],
              label: "",
            },
            {
              title: "Inbox Calendar",
              href: `/docs/components/inbox-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Event Constellation Calendar",
              href: `/docs/components/event-constellation-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Three D Wall Calendar",
              href: `/docs/components/three-dwall-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Task Orbit Calendar",
              href: `/docs/components/task-orbit-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Radial Week View",
              href: `/docs/components/radial-week-view`,
              items: [],
              label: "",
            },
            {
              title: "Stacked Bar Calendar",
              href: `/docs/components/stacked-bar-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Heatmap Calendar",
              href: `/docs/components/heatmap-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Event Calendar",
              href: `/docs/components/event-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Priority Pyramid Calendar",
              href: `/docs/components/priority-pyramid-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Event Path Calendar",
              href: `/docs/components/event-path-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Wheel Of Time Calendar",
              href: `/docs/components/wheel-of-time-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Particle Flow Calendar",
              href: `/docs/components/particle-flow-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Event Aquarium Calendar",
              href: `/docs/components/event-aquarium-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Origami Fold Out Calendar",
              href: `/docs/components/origami-fold-out-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Calendar Planner",
              href: `/docs/components/calendar-planner`,
              items: [],
              label: "",
            },
            {
              title: "Calendar Twin",
              href: `/docs/components/calendar-twin`,
              items: [],
              label: "",
            },
            {
              title: "Chrono Select",
              href: `/docs/components/chrono-select`,
              items: [],
              label: "",
            },
            {
              title: "Pill Calendar",
              href: `/docs/components/pill-calendar`,
              items: [],
              label: "",
            },
            {
              title: "Calendar Scheduler",
              href: `/docs/components/calendar-scheduler`,
              items: [],
              label: "",
            },
            {
              title: "Calendar Lume",
              href: `/docs/components/calendar-lume`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Image Tools",
          items: [
            {
              title: "Image Cropper",
              href: `/docs/components/image-cropper`,
              items: [],
              label: "",
            },
            {
              title: "Advanced Image Uploader",
              href: `/docs/components/advanced-image-uploader`,
              items: [],
              label: "",
            },
            {
              title: "Interactive Image Gallery",
              href: `/docs/components/interactive-image-gallery`,
              items: [],
              label: "",
            },
            {
              title: "Product Image Card",
              href: `/docs/components/product-image-card`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Video Players",
          items: [
            {
              title: "Video Player Pro",
              href: `/docs/components/video-player-pro`,
              items: [],
              label: "",
            },
            {
              title: "Hover Play Card",
              href: `/docs/components/hover-play-card`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Effects",
          items: [
            {
              title: "Container Text Scroll",
              href: `/docs/components/container-text-scroll`,
              items: [],
              label: "",
            },
            {
              title: "Globe",
              href: `/docs/components/globe`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Backgrounds",
          items: [
            {
              title: "Wave Background",
              href: `/docs/components/wave-background`,
              items: [],
              label: "",
            },
            {
              title: "Aurora Flow",
              href: `/docs/components/aurora-flow`,
              items: [],
              label: "",
            },
            {
              title: "Aurora Waves",
              href: `/docs/components/aurora-waves`,
              items: [],
              label: "",
            },
            {
              title: "Falling Symbols Background",
              href: `/docs/components/falling-symbols-background`,
              items: [],
              label: "",
            },
            {
              title: "Spotlight Background",
              href: `/docs/components/spotlight-background`,
              items: [],
              label: "",
            },
            {
              title: "Ripple Distortion",
              href: `/docs/components/ripple-distortion`,
              items: [],
              label: "",
            },
            {
              title: "Particle Field",
              href: `/docs/components/particle-field`,
              items: [],
              label: "",
            },
            {
              title: "Particle Text Dots",
              href: `/docs/components/particle-text-dots`,
              items: [],
              label: "New",
            },
            {
              title: "Rain Background",
              href: `/docs/components/rain-background`,
              items: [],
              label: "",
            },
            {
              title: "Dual Tone Rain Background",
              href: `/docs/components/dual-tone-rain-background`,
              items: [],
              label: "",
            },
            {
              title: "Mouse Spark",
              href: `/docs/components/mouse-spark`,
              items: [],
              label: "",
            },
            {
              title: "Rising Glow",
              href: `/docs/components/rising-glow`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Tabs",
          items: [
            {
              title: "Nested Tabs",
              href: `/docs/components/nested-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Zoom Depth Tabs",
              href: `/docs/components/zoom-depth-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Badge Tabs",
              href: `/docs/components/badge-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Capsule Tabs",
              href: `/docs/components/capsule-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Magnetic Tabs",
              href: `/docs/components/magnetic-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Fade Slide Tabs",
              href: `/docs/components/fade-slide-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Hybrid Tabs",
              href: `/docs/components/hybrid-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Pill Morph Tabs",
              href: `/docs/components/pill-morph-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Sliding Tabs",
              href: `/docs/components/sliding-tabs`,
              items: [],
              label: "",
            },
            {
              title: "Drag And Drop Tabs",
              href: `/docs/components/drag-and-drop-tabs`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Pagination",
          items: [
            {
              title: "Wheel Pagination",
              href: `/docs/components/wheel-pagination`,
              items: [],
              label: "",
            },
            {
              title: "Scroll Pagination",
              href: `/docs/components/scroll-pagination`,
              items: [],
              label: "",
            },
            {
              title: "Icon Pagination",
              href: `/docs/components/icon-pagination`,
              items: [],
              label: "",
            },
            {
              title: "Gooey Pagination",
              href: `/docs/components/gooey-pagination`,
              items: [],
              label: "",
            },
            {
              title: "Stack Pagination",
              href: `/docs/components/stack-pagination`,
              items: [],
              label: "",
            },
            {
              title: "Animated Number Flip",
              href: `/docs/components/animated-number-flip`,
              items: [],
              label: "",
            },
            {
              title: "Morphing Page Dots",
              href: `/docs/components/morphing-page-dots`,
              items: [],
              label: "",
            },
            {
              title: "Sliding Pagination",
              href: `/docs/components/sliding-pagination`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Docks",
          items: [
            {
              title: "Magnetic Dock",
              href: `/docs/components/magnetic-dock`,
              items: [],
              label: "",
            },
            {
              title: "Gooey Dock",
              href: `/docs/components/gooey-dock`,
              items: [],
              label: "",
            },
            {
              title: "Tilted Dock",
              href: `/docs/components/tilted-dock`,
              items: [],
              label: "",
            },
            {
              title: "Dock Morph",
              href: `/docs/components/dock-morph`,
              items: [],
              label: "",
            },
            {
              title: "Dock",
              href: `/docs/components/dock`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "AI Chat Inputs",
          items: [
            {
              title: "AI Chat Input",
              href: `/docs/components/ai-chat-input`,
              items: [],
              label: "",
            },
          ],
        },
      ],
    },
    {
      title: "Section",
      items: [
        {
          title: "FAQs",
          items: [
            {
              title: "StaggeredFAQSection",
              href: `/docs/sections/staggered-faq-section`,
              items: [],
              label: "",
            },
            {
              title: "FeatureHighlights",
              href: `/docs/sections/feature-highlights`,
              items: [],
              label: "",
            },
            {
              title: "FAQ Scroll Accordion",
              href: `/docs/sections/faq-scroll-accordion`,
              items: [],
              label: "",
            },
            {
              title: "FAQ Auto Accordion",
              href: `/docs/sections/faq-auto-accordion`,
              items: [],
              label: "",
            },
            {
              title: "Compact Accordion",
              href: `/docs/sections/compact-accordion`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Hero Sections",
          items: [
            {
              title: "Aurora Hero Section",
              href: `/docs/components/aurora-hero-section`,
              items: [],
              label: "",
            },
            {
              title: "Card Carousel Hero",
              href: `/docs/components/card-carousel-hero`,
              items: [],
              label: "",
            },
            {
              title: "Gradient Hero Showcase",
              href: `/docs/components/gradient-hero-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Spectrum Hero Section",
              href: `/docs/components/spectrum-hero-section`,
              items: [],
              label: "",
            },
            {
              title: "Video Hero Showcase",
              href: `/docs/components/video-hero-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Visionary Hero Section",
              href: `/docs/components/visionary-hero-section`,
              items: [],
              label: "",
            },
            {
              title: "Hero Title Slide",
              href: `/docs/components/hero-title-slide`,
              items: [],
              label: "",
            },
            {
              title: "Hero Section Glass Web",
              href: `/docs/components/hero-section-glass-web`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Featured Section",
          items: [
            {
              title: "Featured Highlights",
              href: `/docs/components/featured-highlights`,
              items: [],
              label: "",
            },
            {
              title: "Feature Grid Section",
              href: `/docs/components/feature-grid-section`,
              items: [],
              label: "",
            },
            {
              title: "Feature Tabs Showcase",
              href: `/docs/components/feature-tabs-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Composite Feature Showcase",
              href: `/docs/components/composite-feature-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Integration And Stats Section",
              href: `/docs/components/integration-and-stats-section`,
              items: [],
              label: "",
            },
            {
              title: "Tech Orbit Showcase",
              href: `/docs/components/tech-orbit-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Partner Integrations Grid",
              href: `/docs/components/partner-integrations-grid`,
              items: [],
              label: "",
            },
            {
              title: "Analytics Dashboard Stats",
              href: `/docs/components/analytics-dashboard-stats`,
              items: [],
              label: "",
            },
            {
              title: "Ruixen Dashboard Stats",
              href: `/docs/components/ruixen-dashboard-stats`,
              items: [],
              label: "",
            },
            {
              title: "Feature Carousel",
              href: `/docs/components/feature-carousel`,
              items: [],
              label: "",
            },
            {
              title: "CRM Insights Panel",
              href: `/docs/components/crm-insights-panel`,
              items: [],
              label: "",
            },
            {
              title: "Multi Orbit Semi Circle",
              href: `/docs/components/multi-orbit-semi-circle`,
              items: [],
              label: "",
            },
            {
              title: "Rotating Gradient Right",
              href: `/docs/components/rotating-gradient-right`,
              items: [],
              label: "",
            },
            {
              title: "Automated Tasks Panel",
              href: `/docs/components/automated-tasks-panel`,
              items: [],
              label: "",
            },
            {
              title: "Case Studies",
              href: `/docs/components/case-studies`,
              items: [],
              label: "",
            },
            {
              title: "Core Value Stats",
              href: `/docs/components/core-value-stats`,
              items: [],
              label: "",
            },
            {
              title: "Feature Slide Showcase",
              href: `/docs/components/feature-slide-showcase`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Client Section",
          items: [
            {
              title: "Trusted Clients Showcase",
              href: `/docs/components/trusted-clients-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Client Carousel Showcase",
              href: `/docs/components/client-carousel-showcase`,
              items: [],
              label: "",
            },
            {
              title: "Auto Scrolling Client Carousel",
              href: `/docs/components/auto-scrolling-client-carousel`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Footer Section",
          items: [
            {
              title: "Footer Pro",
              href: `/docs/components/footer-pro`,
              items: [],
              label: "",
            },
            {
              title: "Corporate Footer",
              href: `/docs/components/corporate-footer`,
              items: [],
              label: "",
            },
            {
              title: "Footer Extended",
              href: `/docs/components/footer-extended`,
              items: [],
              label: "",
            },
            {
              title: "Footer Enterprise",
              href: `/docs/components/footer-enterprise`,
              items: [],
              label: "",
            },
            {
              title: "Footer Mega",
              href: `/docs/components/footer-mega`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Navigation Section",
          items: [
            {
              title: "Hover Gradient Navbar",
              href: `/docs/components/hover-gradient-navbar`,
              items: [],
              label: "",
            },
            {
              title: "Floating Navbar",
              href: `/docs/components/floating-navbar`,
              items: [],
              label: "",
            },
            {
              title: "Luma Bar",
              href: `/docs/components/luma-bar`,
              items: [],
              label: "",
            },
            {
              title: "Promote Header",
              href: `/docs/components/promote-header`,
              items: [],
              label: "",
            },
          ],
        },
        {
          title: "Pricing Section",
          items: [
            {
              title: "Pricing Plans",
              href: `/docs/components/pricing-plans`,
              items: [],
              label: "",
            },
            {
              title: "Pricing Comparison",
              href: `/docs/components/pricing-comparison`,
              items: [],
              label: "",
            },
            {
              title: "Subscription Plans",
              href: `/docs/components/subscription-plans`,
              items: [],
              label: "",
            },
            {
              title: "Pricing Flow",
              href: `/docs/components/pricing-flow`,
              items: [],
              label: "",
            },
            {
              title: "Pricing with User Scaling",
              href: `/docs/components/pricing-with-user-scaling`,
              items: [],
              label: "",
            },
            {
              title: "Pricing Tiers",
              href: `/docs/components/pricing-tiers`,
              items: [],
              label: "",
            },
            {
              title: "Pricing Section Vertical",
              href: `/docs/components/pricing-section-vertical`,
              items: [],
              label: "",
            },
          ],
        },
      ],
    },
  ],
};
