/**
 * Tailwind v4 → v3 source code transform.
 *
 * Converts v4-specific patterns so the component code works in a
 * standard shadcn/ui + Tailwind CSS v3 project.
 *
 * The transform is intentionally conservative — it only touches patterns
 * that are known to break on v3 and leaves everything else untouched.
 */

// shadcn/ui theme tokens whose CSS custom properties follow the pattern:
//   v4: --color-<token>   (auto-generated by @theme)
//   v3: --<token>          (HSL value, wrapped with hsl() at usage)
const SHADCN_THEME_TOKENS = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "border",
  "input",
  "ring",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "sidebar-background",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
];

export function transformToTw3(source: string): string {
  let result = source;

  // 1. Replace var(--color-<TOKEN>) → hsl(var(--<TOKEN>))
  //    Only for known shadcn theme tokens so we don't touch
  //    component-level custom properties like --color-1, --color-from, etc.
  for (const token of SHADCN_THEME_TOKENS) {
    result = result.replaceAll(`var(--color-${token})`, `hsl(var(--${token}))`);
  }

  // 2. Remove v4-only inset-shadow utilities.
  //    In v4, inset-shadow-* and shadow-* are independent layers.
  //    In v3, box-shadow is a single property — mixing them breaks.
  //    The inset shadows used (2xs, white/20) are subtle decorative
  //    accents that are safe to drop for v3 compatibility.
  //    Single regex handles both bare and dark:-prefixed variants.
  //    The [\w/[\].-]+ after the base captures suffixes like white/20.
  result = result.replace(/\b(?:dark:)?inset-shadow-[\w/[\].-]+ ?/g, "");

  return result;
}
